export const API_URL = "http://localhost:8080/api/v1/"
export const PRODUCT = "product"
export const CATEGORY = "category"
export const USER = "user"
export const UPLOAD = "upload"
export const IMAGE = "image"